### ISSUE TITLE
On iOS when using SoreKit method call Purchases.awaitPurchase() returns SuccessfulPurchase which storeTransaction.transactionId doesn't match store transaction_id received from Web hook

### ISSUE THREAD

**Issue by doolle89** [RevenueCat/purchases-kmp#200]
On iOS when we execute successful purchase, the purchase result store transaction id does not match store transaction id received in the web hook:
    val result = Purchases.awaitPurchase() 
    result.storeTransaction.transactionId is some number (1,2,3)
while event sent to the web hook has transaction id like:
    StoreKitTest_Transaction_03d2459cb21c3e7fd65f0cdeb0af12ea_1
    
Revenuecat version: 1.0.0+13.2.0

**Comment by JayShortway** [comment]
Hi, thanks for reporting this! I'm looking into it. Are you using a StoreKit configuration file by any chance? 

If it helps in your situation: on my end, a live sandbox purchase (without a StoreKit configuration file) results in a matching transaction ID in the webhook and the `StoreTransaction` returned by the SDK.

**Comment by JayShortway** [comment]
I confirmed with our backend team that this is expected behavior. When using StoreKit configuration files, the transaction IDs provided by StoreKit are sequential numbers (1, 2, 3), which reset every time you start a new simulator. On the backend, we need to generate unique IDs, which is why you see a different one in the webhook. 

One thing to note is that the suffix in the webhook's transaction ID (`_1`) matches the `StoreTransaction.transactionId` returned by the SDK.

**Comment by doolle89** [comment]
I am using StoreKit file setup according to this tutorial 
https://www.revenuecat.com/blog/engineering/ios-in-app-subscription-tutorial-with-storekit-2-and-swift/

Ok, thanks for the explanation. So in case when StoreKit config file is not used, then the transactionId would match the one in corresponding web hook event?

**Comment by JayShortway** [comment]
Yes, that is correct!

**Comment by doolle89** [comment]
Ok, thanks for info! 
I guess we can close this thread then
